### PR TITLE
More weather info + away temp

### PR DESCRIPTION
**Pull request by bkonings**
Store additional weather info
Add nest away temperature to database and graph

Need changes to database!

### CODE REVIEW

**Comment by bkonings** [comment]
Also note, I have not included the new index.php in this pull request.
That needs work, I'll upload it into my fork but it seemed smart to do the storing of weather data asap.

**Comment by gchenuet** [comment]
Hi @bkonings,

Sorry for the delay...
I'm currently testing your PR but the `getDayTemp_Icon.php` file is missing.
Could you please add it ?

Thanks in advance,
Guillaume

**Comment by bkonings** [comment]
Ah, sorry, I missed that file.
I've added it

**Comment by gchenuet** [comment]
Hi @bkonings,
Sorry for this loooong delay.
I merged some PR since yours, could you please rebase your PR ?

Thanks

**Comment by bkonings** [comment]
I no longer use this, I won't be updating this request.
Closing merge request.

**Pull request closed without merging**
